bedtools unionbedg -i ../GRO_123_minus/GRO_123_trimmed_unm_sorted.bam_negative_norm.bedGraph GRO_1232_trimmed_unm_negative_sorted_norm.bedGraph > GRO_123comb_genome_negative_union.bedGraph
bedtools unionbedg -i ../GRO_125_minus/GRO_125_trimmed_unm_sorted.bam_negative_norm.bedGraph GRO_1252_trimmed_unm_negative_sorted_norm.bedGraph > GRO_125comb_genome_negative_union.bedGraph
bedtools unionbedg -i ../GRO_12C_minus/GRO_12C_trimmed_unm_sorted.bam_negative_norm.bedGraph GRO_12C2_trimmed_unm_negative_sorted_norm.bedGraph > GRO_12Ccomb_genome_negative_union.bedGraph
bedtools unionbedg -i ../GRO_123_plus/GRO_123_trimmed_unm_sorted.bam_positive_norm.bedGraph GRO_1232_trimmed_unm_positive_sorted_norm.bedGraph > GRO_123comb_genome_positive_union.bedGraph
bedtools unionbedg -i ../GRO_125_plus/GRO_125_trimmed_unm_sorted.bam_positive_norm.bedGraph GRO_1252_trimmed_unm_positive_sorted_norm.bedGraph > GRO_125comb_genome_positive_union.bedGraph
bedtools unionbedg -i ../GRO_12C_plus/GRO_12C_trimmed_unm_sorted.bam_positive_norm.bedGraph GRO_12C2_trimmed_unm_positive_sorted_norm.bedGraph > GRO_12Ccomb_genome_positive_union.bedGraph

bedtools unionbedg -i ../GRO_63_minus/GRO_63_trimmed_unm_sorted.bam_negative_norm.bedGraph GRO_632_trimmed_unm_negative_sorted_norm.bedGraph > GRO_63comb_genome_negative_union.bedGraph
bedtools unionbedg -i ../GRO_65_minus/GRO_65_trimmed_unm_sorted.bam_negative_norm.bedGraph GRO_652_trimmed_unm_negative_sorted_norm.bedGraph > GRO_65comb_genome_negative_union.bedGraph
bedtools unionbedg -i ../GRO_6C_minus/GRO_6C_trimmed_unm_sorted.bam_negative_norm.bedGraph GRO_6C2_trimmed_unm_negative_sorted_norm.bedGraph > GRO_6Ccomb_genome_negative_union.bedGraph
bedtools unionbedg -i ../GRO_63_plus/GRO_63_trimmed_unm_sorted.bam_positive_norm.bedGraph GRO_632_trimmed_unm_positive_sorted_norm.bedGraph > GRO_63comb_genome_positive_union.bedGraph
bedtools unionbedg -i ../GRO_65_plus/GRO_65_trimmed_unm_sorted.bam_positive_norm.bedGraph GRO_652_trimmed_unm_positive_sorted_norm.bedGraph > GRO_65comb_genome_positive_union.bedGraph
bedtools unionbedg -i ../GRO_6C_plus/GRO_6C_trimmed_unm_sorted.bam_positive_norm.bedGraph GRO_6C2_trimmed_unm_positive_sorted_norm.bedGraph > GRO_6Ccomb_genome_positive_union.bedGraph